name: Deploy Lab
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          git clone https://github.com/PushpenderIndia/FileUploadWeb
          cd FileUploadWeb
          sudo cp -r 2_content-type /var/www/html
          sudo chmod 777 /var/www/html
          sudo chmod 777 /var/www/html/2_content-type
          sudo chmod 777 /var/www/html/2_content-type/uploads
          sudo service apache2 start&
          npm install -g localtunnel
          sleep 10
          lt --port 80 

      - name: Accessing the tunnel url
        run: sleep 5

