name: Deploy Lab
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd DVFU
          php -S localhost:8000 index.php&

      - name: Expose tunnel
        uses: codetalkio/expose-tunnel@v1.5.0
        id: expose-tunnel
        with:
          service: bore.pub
          port: 8000

      - name: Accessing the tunnel url
        run: echo "Tunnel has been started at '${{ steps.expose-tunnel.outputs.tunnel-url }}'"

      - name: Keep tunnel alive for a defined time
        run: timeout 7200
