name: Deploy Lab
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd Lab
          php -S localhost:8000&
          npm install -g localtunnel
          sleep 20
          lt --port 8000

      - name: Accessing the tunnel url
        run: sleep 5

