name: Deploy Lab
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd Lab
          sudo cp -r upload.php /var/www/html/
          sudo cp -r uploads /var/www/html/
          sudo chmod -R 777 /var/www/html/uploads
          sudo service apache2 start&
          npm install -g localtunnel
          sleep 10
          lt --port 80 

      - name: Accessing the tunnel url
        run: sleep 5

